apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpathpv
  namespace: test-ns
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete    
  hostPath:   
    path: "/mongodbdata"
