apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebappdeployment
  labels:
    app: javawebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebappcontainer
        image: nomrajdevops/java-web-app-docker:17
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
             memory: "356Mi"
             cpu: "300m"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: javawebappvol
          mountPath: "/usr/local/tomcat/conf/tomcat-users.xml"
          subPath: "tomcat-users.xml"
      volumes:
      - name: javawebappvol
        configMap:
          name: javawebappconf
          items:
          - key: "tomcat-users.xml"
            path: "tomcat-users.xml"
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007       
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: javawebappconf
data: 
  tomcat-users.xml: |    
    <?xml version='1.0' encoding='utf-8'?>
    <tomcat-users xmlns="http://tomcat.apache.org/xml"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://tomcat.apache.org/xml tomcat-users.xsd"
              version="1.0">
    <user username="nomraj" password="bujjikanna" roles="admin-gui,manager-gui"/>
    </tomcat-users>
