apiVersion: v1
kind: Namespace
metadata:
  name: devops-ns
  labels:
    app: devops
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkinsapp
  namespace: devops-ns
  labels:
    app: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkinscontainer
        image: jenkins/jenkins:lts
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: jenkinsvol
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkinsvol
        persistentVolumeClaim:
          claimName: jenkinspvc 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkinspvc
  namespace: devops-ns
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: devops-ns
spec:
  type: NodePort
  selector:
    app: jenkins 
  ports:
    - port: 80
      targetPort: 8080

