apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mavenwebapp
  namespace: test-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mavenwebapp
  template:
    metadata:
      name: mavenwebapppod
      labels: 
        app: mavenwebapp
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: name
                operator: In
                values:
                - workerOne        
      containers:
      - name: mavenwebappcontainer
        image: nomrajdevops/maven-web-application:2
        ports:
        - containerPort: 8080 
---
apiVersion: v1
kind: Service
metadata:
   name: mavenwebappsvc
   namespace: test-ns
spec:
   type: NodePort
   selector:
     app: mavenwebapp
   ports:
   - port: 80
     targetPort: 8080
