apiVersion: v1
kind: Pod
metadata:
  name: testpod
  labels:
    app: mavenwebapp
spec:
  containers:
  - name: mavenwebappcontainer
    image: nomrajdocker/maven-web-application:1
    ports:
    -  containerPort: 8080
  - name: nginxcontainer
    image: nginx
    ports:
    - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: testsvc
spec:
  type: NodePort
  selector:
    app: mavenwebapp
  ports:
  - port: 8080
    targetPort: 8080
    name: tomcat
  - port: 80
    targetPort: 80
    name: nginx    
