apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfspv
  namespace: test-ns
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.31.33.112     
    path: "/mnt/nfs-share"
