apiVersion: v1
kind: Pod
metadata: 
  name: nodejspod
  labels:
    app: nodejs
  namespace: test-ns
spec:
  containers:
  - name: nodejscontainer
    image: nomrajdocker/nodejs-app-bujji:1
    ports:
    - containerPort: 9981
---
apiVersion: v1
kind: Service
metadata:
  name: nodejsvc 
  namespace: test-ns
spec:
  type: NodePort
  selector: 
    app: nodejs
  ports:
  - port: 80
    targetPort: 9981 
